apiVersion: v1
kind: ConfigMap
metadata:
  name: mt3gateway-config
  namespace: {{ .Values.namespace }}
data:
  FAILURE_RATE: "55"
  RETRIES: "10"
  APPINSIGHTS_INSTRUMENTATIONKEY: "950301e2-21ea-4ac9-b333-5b76d19b898b"